--- #YAML:1.0
name:               CDB-TinyCDB
version:            0.05
abstract:           Perl extension for TinyCDB library to cdb databases
author:
    - Alex J. G. Burzyński <ajgb@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Test::Exception:   0
    Test::More:        0
    Test::NoWarnings:  0
requires:
    XSLoader:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
